[package]
name = "media-plugin"
version = "0.0.2"
edition = "2021"
publish = false

[[bin]]
name = "media"
path = "src/main.rs"

[dependencies]
veyron-sdk = "0.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zbus = { version = "4", default-features = false, features = ["tokio"] }
zvariant = "4"
anyhow = "1"
async-trait = "0.1"
